// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/flash-sales": {
    params: {};
  };
  "/product/:id": {
    params: {
      "id": string;
    };
  };
  "/sellers": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/products": {
    params: {};
  };
  "/admin/orders": {
    params: {};
  };
  "/admin/customers": {
    params: {};
  };
  "/admin/vendors": {
    params: {};
  };
  "/admin/vendor-profile": {
    params: {};
  };
  "/admin/logs": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/hello-world": {
    params: {};
  };
  "/blog/sensor-staircase-lights": {
    params: {};
  };
  "/:slug": {
    params: {
      "slug": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/flash-sales" | "/product/:id" | "/sellers" | "/auth" | "/checkout" | "/account" | "/privacy-policy" | "/terms" | "/faq" | "/admin" | "/admin/products" | "/admin/orders" | "/admin/customers" | "/admin/vendors" | "/admin/vendor-profile" | "/admin/logs" | "/admin/settings" | "/blog" | "/blog/hello-world" | "/blog/sensor-staircase-lights" | "/:slug" | "/*";
  };
  "pages/Index.tsx": {
    id: "pages/Index";
    page: "/";
  };
  "pages/Products.tsx": {
    id: "pages/Products";
    page: "/products";
  };
  "pages/FlashSalesPage.tsx": {
    id: "pages/FlashSalesPage";
    page: "/flash-sales";
  };
  "pages/ProductPage.tsx": {
    id: "pages/ProductPage";
    page: "/product/:id";
  };
  "pages/VendorsPage.tsx": {
    id: "pages/VendorsPage";
    page: "/sellers";
  };
  "pages/AuthPage.tsx": {
    id: "pages/AuthPage";
    page: "/auth";
  };
  "pages/CheckoutPage.tsx": {
    id: "pages/CheckoutPage";
    page: "/checkout";
  };
  "pages/AccountPage.tsx": {
    id: "pages/AccountPage";
    page: "/account";
  };
  "pages/PrivacyPolicy.tsx": {
    id: "pages/PrivacyPolicy";
    page: "/privacy-policy";
  };
  "pages/TermsOfUse.tsx": {
    id: "pages/TermsOfUse";
    page: "/terms";
  };
  "pages/FAQ.tsx": {
    id: "pages/FAQ";
    page: "/faq";
  };
  "pages/admin/AdminDashboard.tsx": {
    id: "pages/admin/AdminDashboard";
    page: "/admin" | "/admin/products" | "/admin/orders" | "/admin/customers" | "/admin/vendors" | "/admin/vendor-profile" | "/admin/logs" | "/admin/settings";
  };
  "pages/admin/AdminHome.tsx": {
    id: "pages/admin/AdminHome";
    page: "/admin";
  };
  "pages/admin/AdminProducts.tsx": {
    id: "pages/admin/AdminProducts";
    page: "/admin/products";
  };
  "pages/admin/AdminOrders.tsx": {
    id: "pages/admin/AdminOrders";
    page: "/admin/orders";
  };
  "pages/admin/AdminCustomers.tsx": {
    id: "pages/admin/AdminCustomers";
    page: "/admin/customers";
  };
  "pages/admin/AdminVendors.tsx": {
    id: "pages/admin/AdminVendors";
    page: "/admin/vendors";
  };
  "pages/admin/AdminVendorProfile.tsx": {
    id: "pages/admin/AdminVendorProfile";
    page: "/admin/vendor-profile";
  };
  "pages/admin/AdminLogs.tsx": {
    id: "pages/admin/AdminLogs";
    page: "/admin/logs";
  };
  "pages/admin/AdminSettings.tsx": {
    id: "pages/admin/AdminSettings";
    page: "/admin/settings";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "blog/hello-world.mdx": {
    id: "blog/hello-world";
    page: "/blog/hello-world";
  };
  "blog/sensor-staircase-lights.mdx": {
    id: "blog/sensor-staircase-lights";
    page: "/blog/sensor-staircase-lights";
  };
  "pages/VendorPage.tsx": {
    id: "pages/VendorPage";
    page: "/:slug";
  };
  "pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Index": typeof import("./src/pages/Index.tsx");
  "pages/Products": typeof import("./src/pages/Products.tsx");
  "pages/FlashSalesPage": typeof import("./src/pages/FlashSalesPage.tsx");
  "pages/ProductPage": typeof import("./src/pages/ProductPage.tsx");
  "pages/VendorsPage": typeof import("./src/pages/VendorsPage.tsx");
  "pages/AuthPage": typeof import("./src/pages/AuthPage.tsx");
  "pages/CheckoutPage": typeof import("./src/pages/CheckoutPage.tsx");
  "pages/AccountPage": typeof import("./src/pages/AccountPage.tsx");
  "pages/PrivacyPolicy": typeof import("./src/pages/PrivacyPolicy.tsx");
  "pages/TermsOfUse": typeof import("./src/pages/TermsOfUse.tsx");
  "pages/FAQ": typeof import("./src/pages/FAQ.tsx");
  "pages/admin/AdminDashboard": typeof import("./src/pages/admin/AdminDashboard.tsx");
  "pages/admin/AdminHome": typeof import("./src/pages/admin/AdminHome.tsx");
  "pages/admin/AdminProducts": typeof import("./src/pages/admin/AdminProducts.tsx");
  "pages/admin/AdminOrders": typeof import("./src/pages/admin/AdminOrders.tsx");
  "pages/admin/AdminCustomers": typeof import("./src/pages/admin/AdminCustomers.tsx");
  "pages/admin/AdminVendors": typeof import("./src/pages/admin/AdminVendors.tsx");
  "pages/admin/AdminVendorProfile": typeof import("./src/pages/admin/AdminVendorProfile.tsx");
  "pages/admin/AdminLogs": typeof import("./src/pages/admin/AdminLogs.tsx");
  "pages/admin/AdminSettings": typeof import("./src/pages/admin/AdminSettings.tsx");
  "routes/blog": typeof import("./src/routes/blog.tsx");
  "blog/hello-world": typeof import("./src/blog/hello-world.mdx");
  "blog/sensor-staircase-lights": typeof import("./src/blog/sensor-staircase-lights.mdx");
  "pages/VendorPage": typeof import("./src/pages/VendorPage.tsx");
  "pages/NotFound": typeof import("./src/pages/NotFound.tsx");
};